# 异常

异常是一种运行期状态值。当程序出现错误或返回非预期结果时，通常会抛出一个异常对象来表达非正常状态。

python 中的异常对象被保存到当前线程状态里，其可用 `sys.exc_info` 获取：

```python
def test():
    try:
        raise Exception("err")
    except:
        print(sys.exc_info())

test()
# (<class 'Exception'>, Exception('err), <traceback object at ...>)
```

## 异常处理流程

完整的异常处理结构包含 4 个组成单元：

```python
def test(n):
    try:
        # 需要保护的代码块
        print("try")
        if not n: raise Exception
    except:
        # 根据所属异常类型捕获并处理
        print("except")
    else:
        # 异常未发生时执行
        print("else")
    finally:
        # 无论异常是否发生，总是执行
        print("finally")
```

使用 `raise` 语句主动抛出异常，但必须是 `BaseException` 子类或实例。

所导出的异常实例名字在语句块结束时，会被自动删除，这与普通名字作用域不同。

## 自定义异常

按逻辑分类构建异常类型树，实现以不同粒度捕获异常。建议以 `Exception`, `Error` 后缀区分可修复异常和不可修复错误。

## 异常的使用模式

除用于错误和非正常状态处理外，异常还可以用来控制执行流程：

- 从多重嵌套循环中填出
- 终止多级函数调用过程
- 向生成器对象发送异常
- 使用 warnings 模块输出警告信息

## 断言

断言是防御性编程使用的一项技术，其根本目标时保护代码本身，而非用户逻辑。除检查参数外，断言有时也用来检查上下文状态。

在命令行下以 `-O` 或 `-OO` 参数启动解释器优化模式后，编译器会直接忽略断言语句，甚至不会为其生成字节码。

```python
assert expression1, expression2

# 实际行为如下：
if __debug__:
    if not expression1: raise AssertionError(expression2)
```

## 上下文（with 语句）

上下文管理协议是对异常处理结构的一种包装：

```python
with expression as x:
    suite

# 实际行为以伪代码表示如下：
o = expression()  # 创建上下文对象
x = o.__enter__()  # 执行 __enter__，将返回值赋值给 x

try:
    suite  # 执行用户代码
except:
    typ, val, tb = sys.exc_info()  # 拦截异常，传递给 __exit__
finally:
    if not o.__exit__(typ, val, tb):  # 确保 __exit__ 总被执行
        raise val  # 若 __exit__ 返回 False，则重现抛出异常
```

可同时使用多个上下文对象，多个 `__exit__` 按 FILO 顺序执行。

### contextlib

上下文对象需要创建类型，并实现协议方法，可借助 `contextlib.contextmanager` 创建上下文对象：

```python
# contextmanager 利用了生成器的分步执行能力
# 精简后的示意代码：
class GeneratorContextManager:
    def __init__(self, func):
        self.gen = func()

    def __enter__(self):
        return next(self.gen)  #  启动生成器，执行 yield 之前的用户代码，返回 yield 结果

    def __exit__(self, typ, val, tb):
        if typ is None:
            next(self.gen)  # 继续执行 yield 后面的代码
        else:
            self.gen.throw(typ, val, tb)  # 若发生异常，则将异常抛回给生成器

```
